import { Inter } from "next/font/google";
import "./globals.css";

import '@fortawesome/fontawesome-svg-core/styles.css'
import { config } from '@fortawesome/fontawesome-svg-core'
config.autoAddCss = false // Prevent FontAwesome from adding its own CSS

import Link from 'next/link'

import Image from 'next/image'


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Chloe Jadyn",
  description: "Generated by create next app",
};

function Navbar() {
  return (
    <div className="flex items-center justify-between px-8 py-4 bg-[#fefcf7] shadow-sm">
      {/* Logo */}
      <Link href="/">
        <Image
          src="assets/home/navbar_logo.png" // Replace with the actual path to your logo
          alt="Logo"
          className="h-auto max-h-16 w-auto object-contain" // Dynamically adjusts size
        />
      </Link>

      {/* Navigation Links */}
      <div className="hidden md:flex gap-3">
        <Link href="/works">
          <div className="text-lg border border-solid border-black px-3 py-1 rounded-full">
            WORKS
          </div>
        </Link>
        <Link href="/about">
          <div className="text-lg border border-solid border-black px-3 py-1 rounded-full">
            ABOUT
          </div>
        </Link>
      </div>

      {/* Mobile Menu Button */}
      <button className="inline-flex items-center w-6 h-6 justify-center text-sm text-gray-500 rounded-lg md:hidden">
        <svg viewBox="0 0 100 80" width="40" height="40">
          <rect width="100" height="10" rx="10"></rect>
          <rect y="30" width="100" height="10" rx="10"></rect>
          <rect y="60" width="100" height="10" rx="10"></rect>
        </svg>
      </button>
    </div>
  );
}

function Footer() {
  return (
    <div className="flex items-center justify-between px-8 py-4 bg-[#fefcf7] text-lg">
      {/* Logo */}
      <Image
        src="assets/home/navbar_logo.png" // Replace with the actual path to your logo
        alt="Logo"
        className="h-auto max-h-12 w-auto object-contain" // Ensures proper scaling and aspect ratio
      />

      {/* Copyright */}
      <p>&#169; CHLOE JADYN CARANDANG, 2024</p>

      {/* CV Request */}
      <Link href="mailto:carandangcn@students.national-u.edu.ph"><p className="cursor-pointer hover:underline">REQUEST CV</p></Link>
    </div>
  );
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
